### ISSUE TITLE
It's all in python-hearthstone

### ISSUE THREAD

**Issue by jleclanche** [lamperi/hearthstone-deck-format#1]
Hey,

Try `pip install hearthstone`:

https://github.com/HearthSim/python-hearthstone/blob/master/hearthstone/deckstrings.py

The `deckstrings.parse_deckstring()` function will return a tuple of `cards, heroes, format`. `cards` is a list of DBF IDs of the cards, same for `heroes`. `format` is a `hearthstone.enums.FormatType` IntEnum.

Works only on python 3.

**Comment by lamperi** [comment]
Looks much more comprehensive implementation what I could do! I wonder if this was this reverse engineered from HS client code or are there more examples around?

**Comment by jleclanche** [comment]
There's no client code available yet. We had some help from Blizzard.

**Comment by jleclanche** [comment]
Swing by https://discord.gg/hearthsim-devs some time if you're curious :)
